### ISSUE TITLE
After Update suddenly the script doesn't find basestations anymore.

### ISSUE THREAD

**Issue by kubax** [DavidRisch/steamvr_utils#22] opened 2023-08-04 14:46 UTC
Hi,

after i updated my Arch Linux recently, the script doesn't seem to find the basestations anymore.

I have a feeling it has to do with a Python update to 3.11.3 but i can't seem to find the exact problem.

Here is a log from a recent try to activate the basestations, wich prior to updateing some weeks ago worked perfectly fine. Also i can use a android app to activate the basestations, so the stations are fine.

Any ideas what could be the problem here?

```
2023-08-04 16:34:42 [INFO ]: steamvr_utils version: 1.1.1
2023-08-04 16:34:42 [DEBUG]: dry_run: False
2023-08-04 16:34:42 [INFO ]: SteamvrUtils turning on:
2023-08-04 16:34:42 [INFO ]: Scanning for Base Stations:
2023-08-04 16:34:44 [ERROR]: Failure of attempt 1 of 5: Bluetooth scan found no Base Stations. If there are powered Base Stations near you, this is probably a problem with your Bluetooth device.
2023-08-04 16:34:47 [ERROR]: Failure of attempt 2 of 5: Bluetooth scan found no Base Stations. If there are powered Base Stations near you, this is probably a problem with your Bluetooth device.
2023-08-04 16:34:49 [ERROR]: Failure of attempt 3 of 5: Bluetooth scan found no Base Stations. If there are powered Base Stations near you, this is probably a problem with your Bluetooth device.
2023-08-04 16:34:52 [ERROR]: Failure of attempt 4 of 5: Bluetooth scan found no Base Stations. If there are powered Base Stations near you, this is probably a problem with your Bluetooth device.
2023-08-04 16:34:54 [ERROR]: Failure of attempt 5 of 5: Bluetooth scan found no Base Stations. If there are powered Base Stations near you, this is probably a problem with your Bluetooth device.
2023-08-04 16:34:55 [ERROR]: No successful attempt in any of the 5 attempts. Last error:
2023-08-04 16:34:55 [ERROR]: 
Traceback (most recent call last):
  File "/home/kubax/bin/steamvr_utils/scripts/steamvr_utils.py", line 133, in main
    steamvr_utils.action(selected_action)
  File "/home/kubax/bin/steamvr_utils/scripts/steamvr_utils.py", line 47, in action
    self.turn_on()
  File "/home/kubax/bin/steamvr_utils/scripts/steamvr_utils.py", line 72, in turn_on
    self.basestation_power_interface.action(basestation_interface.Action.ON)
  File "/home/kubax/bin/steamvr_utils/scripts/basestation_interface/v2_interface.py", line 129, in action
    attempt_loop(lambda: self.scan(), self.config.basestation_attempt_count_scan())
  File "/home/kubax/bin/steamvr_utils/scripts/basestation_interface/v2_interface.py", line 126, in attempt_loop
    raise last_error
  File "/home/kubax/bin/steamvr_utils/scripts/basestation_interface/v2_interface.py", line 114, in attempt_loop
    return function()
           ^^^^^^^^^^
  File "/home/kubax/bin/steamvr_utils/scripts/basestation_interface/v2_interface.py", line 129, in <lambda>
    attempt_loop(lambda: self.scan(), self.config.basestation_attempt_count_scan())
                         ^^^^^^^^^^^
  File "/home/kubax/bin/steamvr_utils/scripts/basestation_interface/v2_interface.py", line 77, in scan
    raise RuntimeError('Bluetooth scan found no Base Stations. '
RuntimeError: Bluetooth scan found no Base Stations. If there are powered Base Stations near you, this is probably a problem with your Bluetooth device.
```

**Comment by DavidRisch** [comment] 2023-08-04 15:10
I haven't used my VR device in quite some time and am still running python 3.8. But I plan to upgrade my disto in a few days and will test the scripts then.

**Comment by DavidRisch** [comment] 2023-08-17 22:36
I can reproduce your problem. On Ubuntu 20.04 with python 3.8 everything works and on arch with python 3.11 it fails to find the base stations (exact same error message).
In order to narrow down the problem I also tried using another python blutooth low energy library (bleak) and that also did not work. I will look into this further tomorrow.

**Comment by DavidRisch** [comment] 2023-08-18 13:05
I noticed that in the list of bluetooth devices in gnome settings only very few devices showed up. Lokking at `dmesg` there were some blutooth related error message which lead me here: https://bugzilla.kernel.org/show_bug.cgi?id=217651 (I have not confirmed if the issue is the exact same, but it is similar)
Using an older kernel (`6.1.45-1-lts` from `pacman -S linux-lts`) everthing works: more/all devices show up in gnome settings, and I can controll the basestations from python. So it seems to be a combination of my particular blutooth device and newer kernel versions which causes the issue

I will close this issue because it is caused by something upstream and cannot be fixed here.

**Closed as completed by DavidRisch** 2023-08-18 13:05 UTC

**Comment by kubax** [comment] 2023-08-18 13:13
Nice find, that might also be the reason for another "problem" i got yesterday, when trying to reverse engineer a BLE cat fountain. i just thought the device is faulty or picky...

also sorry for blaming your script, because i realy love it!! espacially that i could automate it with steamvr commandline..
